# Generated by Django 5.2 on 2025-05-04 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Truck', 'Truck'), ('Van', 'Van'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Other', 'Other')], max_length=20)),
                ('car_category', models.CharField(choices=[('Economy', 'Economy'), ('Luxury', 'Luxury'), ('Sports', 'Sports'), ('Off-road', 'Off-road'), ('Electric', 'Electric'), ('Other', 'Other')], max_length=20)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('transmission_type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Other', 'Other')], max_length=10)),
                ('current_odometer_reading', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('current_status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('InUse', 'InUse'), ('UnderMaintenance', 'UnderMaintenance')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarRentalOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_without_driver', models.BooleanField(default=False)),
                ('available_with_driver', models.BooleanField(default=False)),
                ('daily_rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_rental_price_with_driver', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_price_with_driver', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_price_with_driver', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_options', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_history_count', models.IntegerField(default=0)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarUsagePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_km_limit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('extra_km_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daily_hour_limit', models.IntegerField(blank=True, null=True)),
                ('extra_hour_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_policy', to='cars.car')),
            ],
        ),
    ]
