# Generated by Django 5.2 on 2025-06-24 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfDriveRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_km_limit', models.PositiveIntegerField(default=200, help_text='Daily kilometer limit for the rental')),
                ('actual_dropoff_time', models.DateTimeField(blank=True, help_text='Actual dropoff time recorded at end of rental', null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfdrive_rentals', to='cars.car')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfdrive_rentals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfDrivePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_paid_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded'), ('No Remaining to Refund', 'No Remaining to Refund')], default='Pending', max_length=30)),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('deposit_refunded_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded'), ('No Remaining to Refund', 'No Remaining to Refund')], default='Pending', max_length=30)),
                ('deposit_refunded_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_refund_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_paid_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded'), ('No Remaining to Refund', 'No Remaining to Refund')], default='Pending', max_length=30)),
                ('remaining_paid_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ctw_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctw_paid_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded'), ('No Remaining to Refund', 'No Remaining to Refund')], default='Pending', max_length=30)),
                ('ctw_paid_at', models.DateTimeField(blank=True, null=True)),
                ('ctw_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('PayPal', 'PayPal')], default='Cash', max_length=10)),
                ('rental_total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount after adding any extra costs at the end of rental', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='selfdrive_rentals.selfdriverental')),
            ],
        ),
        migrations.CreateModel(
            name='SelfDriveOdometerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='selfdrive/odometers/')),
                ('value', models.FloatField(help_text='Odometer reading at this point')),
                ('type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_images', to='selfdrive_rentals.selfdriverental')),
            ],
        ),
        migrations.CreateModel(
            name='SelfDriveLiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_locations', to='selfdrive_rentals.selfdriverental')),
            ],
        ),
        migrations.CreateModel(
            name='SelfDriveContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_by_renter', models.BooleanField(default=False)),
                ('signed_by_owner', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='selfdrive/contracts/')),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='selfdrive_rentals.selfdriverental')),
            ],
        ),
        migrations.CreateModel(
            name='SelfDriveRentalBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_km', models.FloatField(default=0)),
                ('daily_price', models.FloatField(default=0)),
                ('extra_km_cost', models.FloatField(default=0)),
                ('allowed_km', models.FloatField(default=0)),
                ('extra_km', models.FloatField(default=0)),
                ('base_cost', models.FloatField(default=0)),
                ('ctw_fee', models.FloatField(default=0)),
                ('late_fee', models.FloatField(default=0)),
                ('final_cost', models.FloatField(default=0)),
                ('commission_rate', models.FloatField(default=0.2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='selfdrive_rentals.selfdriverental')),
            ],
        ),
    ]
