# Generated by Django 5.2 on 2025-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdrive_rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfdriverental',
            old_name='dropoff_location',
            new_name='dropoff_address',
        ),
        migrations.RenameField(
            model_name='selfdriverental',
            old_name='pickup_location',
            new_name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='selfdriverental',
            name='daily_km_limit',
        ),
        migrations.AddField(
            model_name='selfdriverental',
            name='allowed_km',
            field=models.FloatField(default=0, help_text='Total allowed kilometers for the rental'),
        ),
        migrations.AddField(
            model_name='selfdriverental',
            name='dropoff_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='selfdriverental',
            name='dropoff_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='selfdriverental',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='selfdriverental',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
