# Generated by Django 5.2 on 2025-06-24 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdrive_rentals', '0002_rename_dropoff_location_selfdriverental_dropoff_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfdriverentalbreakdown',
            old_name='planned_km',
            new_name='driver_earnings',
        ),
        migrations.RemoveField(
            model_name='selfdriverental',
            name='allowed_km',
        ),
        migrations.AddField(
            model_name='selfdriverentalbreakdown',
            name='num_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='selfdriverentalbreakdown',
            name='platform_earnings',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='SelfDriveRentalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start_trip', 'Start Trip'), ('end_trip', 'End Trip'), ('payment', 'Payment'), ('confirm_handover', 'Confirm Handover'), ('status_change', 'Status Change')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='selfdrive_rentals.selfdriverental')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfDriveRentalStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=32)),
                ('new_status', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='selfdrive_rentals.selfdriverental')),
            ],
        ),
    ]
