# Generated by Django 5.2 on 2025-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdrive_rentals', '0003_rename_planned_km_selfdriverentalbreakdown_driver_earnings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfdriverental',
            name='actual_dropoff_time',
        ),
        migrations.AddField(
            model_name='selfdriverentalbreakdown',
            name='actual_dropoff_time',
            field=models.DateTimeField(blank=True, help_text='Actual dropoff time recorded at end of rental', null=True),
        ),
    ]
