# Generated by Django 5.2 on 2025-06-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdrive_rentals', '0004_remove_selfdriverental_actual_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfdriverentalbreakdown',
            name='extra_km_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='selfdriverentalbreakdown',
            name='initial_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='selfdriverentalbreakdown',
            name='late_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selfdriverentalbreakdown',
            name='total_extras_cost',
            field=models.FloatField(default=0),
        ),
    ]
