# Generated by Django 5.2 on 2025-06-24 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdrive_rentals', '0005_selfdriverentalbreakdown_extra_km_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfdrivecontract',
            old_name='signed_by_owner',
            new_name='owner_signed',
        ),
        migrations.RenameField(
            model_name='selfdrivecontract',
            old_name='signed_at',
            new_name='owner_signed_at',
        ),
        migrations.RenameField(
            model_name='selfdrivecontract',
            old_name='signed_by_renter',
            new_name='renter_signed',
        ),
        migrations.RenameField(
            model_name='selfdrivepayment',
            old_name='ctw_paid_at',
            new_name='deposit_due_at',
        ),
        migrations.RemoveField(
            model_name='selfdrivecontract',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='selfdrivepayment',
            name='ctw_amount',
        ),
        migrations.RemoveField(
            model_name='selfdrivepayment',
            name='ctw_paid_status',
        ),
        migrations.RemoveField(
            model_name='selfdrivepayment',
            name='ctw_transaction_id',
        ),
        migrations.RemoveField(
            model_name='selfdrivepayment',
            name='deposit_refunded_status',
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='contract_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='owner_contract_image',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/owner_signed/'),
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='renter_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='selfdrivepayment',
            name='deposit_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selfdrivepayment',
            name='excess_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='selfdrivepayment',
            name='excess_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfdrivepayment',
            name='excess_paid_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=16),
        ),
        migrations.AddField(
            model_name='selfdrivepayment',
            name='excess_transaction_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='selfdrivepayment',
            name='deposit_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='selfdrivepayment',
            name='deposit_paid_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], default='Pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='selfdrivepayment',
            name='deposit_refund_transaction_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='selfdrivepayment',
            name='deposit_transaction_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='selfdrivepayment',
            name='payment_method',
            field=models.CharField(choices=[('visa', 'Visa'), ('wallet', 'Wallet'), ('cash', 'Cash')], default='cash', max_length=16),
        ),
        migrations.AlterField(
            model_name='selfdrivepayment',
            name='remaining_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='selfdrivepayment',
            name='remaining_paid_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Confirmed', 'Confirmed')], default='Pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='selfdrivepayment',
            name='remaining_transaction_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='selfdrivepayment',
            name='rental_total_amount',
            field=models.FloatField(default=0),
        ),
    ]
