# Generated by Django 5.2 on 2025-06-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdrive_rentals', '0006_rename_signed_by_owner_selfdrivecontract_owner_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfdriverental',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('PendingOwnerConfirmation', 'PendingOwnerConfirmation'), ('Confirmed', 'Confirmed'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], default='Pending', max_length=32),
        ),
    ]
