# Generated by Django 5.2 on 2025-06-26 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfdrive_rentals', '0007_alter_selfdriverental_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfdrivecontract',
            name='owner_pickup_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='owner_pickup_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='owner_return_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='owner_return_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='renter_pickup_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='renter_pickup_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='renter_return_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selfdrivecontract',
            name='renter_return_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selfdriverentallog',
            name='action',
            field=models.CharField(choices=[('create_rental', 'Create Rental'), ('owner_confirm', 'Owner Confirm'), ('deposit_paid', 'Deposit Paid'), ('owner_pickup_handover', 'Owner Pickup Handover'), ('renter_pickup_handover', 'Renter Pickup Handover'), ('trip_started', 'Trip Started'), ('location_requested', 'Location Requested'), ('renter_dropoff_handover', 'Renter Dropoff Handover'), ('owner_dropoff_handover', 'Owner Dropoff Handover'), ('trip_finished', 'Trip Finished'), ('canceled', 'Canceled')], max_length=32),
        ),
        migrations.CreateModel(
            name='SelfDriveCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('type', models.CharField(choices=[('pickup', 'Pickup'), ('return', 'Return')], max_length=10)),
                ('uploaded_by', models.CharField(choices=[('renter', 'Renter'), ('owner', 'Owner')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_images', to='selfdrive_rentals.selfdriverental')),
            ],
        ),
    ]
