# Generated by Django 5.2.3 on 2025-06-26 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_order_id', models.CharField(help_text='Your internal store order ID.', max_length=255, unique=True)),
                ('paymob_transaction_id', models.CharField(blank=True, help_text='Transaction ID from Paymob.', max_length=255, null=True, unique=True)),
                ('paymob_order_id', models.CharField(blank=True, help_text='Order ID from Paymob.', max_length=255, null=True)),
                ('amount_cents', models.IntegerField(help_text='Amount in cents (e.g., 7000 for 70 EGP).')),
                ('currency', models.CharField(default='EGP', help_text='Currency, defaults to EGP.', max_length=10)),
                ('success', models.BooleanField(default=False, help_text='Was the transaction successful?')),
                ('message', models.TextField(blank=True, help_text='Error or success message from Paymob.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the transaction record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to the transaction record.')),
                ('payment_method', models.CharField(blank=True, help_text="Payment method (e.g., 'card' or 'wallet').", max_length=50, null=True)),
                ('status', models.CharField(default='pending', help_text="Transaction status (e.g., 'pending', 'completed', 'failed').", max_length=50)),
                ('card_type', models.CharField(blank=True, help_text="Type of card (e.g., 'Visa', 'MasterCard').", max_length=50, null=True)),
                ('card_pan', models.CharField(blank=True, help_text='Last 4 digits of the card number.', max_length=50, null=True)),
                ('user', models.ForeignKey(help_text='The user who performed the transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'unique_together': {('user', 'merchant_order_id')},
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='The card token provided by Paymob.', max_length=255, unique=True)),
                ('card_brand', models.CharField(blank=True, help_text="Brand of the card (e.g., 'Visa', 'MasterCard').", max_length=50, null=True)),
                ('card_last_four_digits', models.CharField(blank=True, help_text='Last four digits of the card.', max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the card was saved.')),
                ('user', models.ForeignKey(help_text='The user to whom the saved card belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Card',
                'verbose_name_plural': 'Saved Cards',
                'unique_together': {('user', 'token')},
            },
        ),
    ]
