# Generated by Django 5.2 on 2025-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_fix_balance_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='phone_wallet_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
