# Generated by Django 5.2 on 2025-06-23 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Confirmed', 'Confirmed'), ('Awaiting Deposit', 'Awaiting Deposit'), ('Deposit Paid', 'Deposit Paid'), ('Awaiting Contract', 'Awaiting Contract'), ('contractSigned', 'Contract Signed'), ('Awaiting Final Payment', 'Awaiting Final Payment'), ('Final Payment Paid', 'Final Payment Paid'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default='Pending', max_length=30)),
                ('rental_type', models.CharField(choices=[('WithDriver', 'With Driver'), ('WithoutDriver', 'Without Driver')], default='WithDriver', max_length=20)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_address', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(choices=[('wallet', 'Wallet'), ('visa', 'Visa/Mastercard'), ('cash', 'Cash')], default='cash', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='cars.car')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_polyline', models.TextField(blank=True, null=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planned_trip', to='rentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='RentalBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_km', models.FloatField(default=0)),
                ('total_waiting_minutes', models.IntegerField(default=0)),
                ('daily_price', models.FloatField(default=0)),
                ('extra_km_cost', models.FloatField(default=0)),
                ('waiting_cost', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('buffer_amount', models.FloatField(default=0)),
                ('deposit', models.FloatField(default=0)),
                ('platform_fee', models.FloatField(default=0)),
                ('driver_earnings', models.FloatField(default=0)),
                ('allowed_km', models.FloatField(default=0)),
                ('extra_km', models.FloatField(default=0)),
                ('base_cost', models.FloatField(default=0)),
                ('final_cost', models.FloatField(default=0)),
                ('commission_rate', models.FloatField(default=0.2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='rentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='RentalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('performed_by_type', models.CharField(choices=[('System', 'System'), ('Owner', 'Owner'), ('Renter', 'Renter')], default='System', max_length=10)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_logs', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_paid_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded')], default='Pending', max_length=30)),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('deposit_refunded_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded')], default='Pending', max_length=30)),
                ('deposit_refunded_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_refund_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_paid_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded')], default='Pending', max_length=30)),
                ('remaining_paid_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('limits_excess_insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limits_refunded_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded')], default='Pending', max_length=30)),
                ('limits_refunded_at', models.DateTimeField(blank=True, null=True)),
                ('limits_refund_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('PayPal', 'PayPal')], default='Cash', max_length=10)),
                ('rental_total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount after adding any extra costs at the end of rental', max_digits=10)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='rentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='RentalUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('end_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_distance_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_return_time', models.DateTimeField(blank=True, null=True)),
                ('extra_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('extra_km_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('extra_hour_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pickup_confirmed_by_owner', models.BooleanField(blank=True, default=False, null=True)),
                ('pickup_confirmed_by_renter', models.BooleanField(blank=True, default=False, null=True)),
                ('dropoff_confirmed_by_owner', models.BooleanField(blank=True, default=False, null=True)),
                ('dropoff_confirmed_by_renter', models.BooleanField(blank=True, default=False, null=True)),
                ('total_waiting_minutes', models.IntegerField(default=0)),
                ('extra_waiting_minutes', models.IntegerField(default=0)),
                ('waiting_time_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_info', to='rentals.rental')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedTripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('approx_waiting_time_minutes', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('actual_waiting_minutes', models.PositiveIntegerField(default=0)),
                ('waiting_started_at', models.DateTimeField(blank=True, null=True)),
                ('waiting_ended_at', models.DateTimeField(blank=True, null=True)),
                ('location_verified', models.BooleanField(default=False)),
                ('planned_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rentals.plannedtrip')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('planned_trip', 'stop_order')},
            },
        ),
    ]
