# Generated by Django 5.2 on 2025-06-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalusage',
            old_name='extra_hour_charges',
            new_name='total_waiting_time',
        ),
        migrations.RemoveField(
            model_name='rentalbreakdown',
            name='buffer_amount',
        ),
        migrations.RemoveField(
            model_name='rentalusage',
            name='actual_return_time',
        ),
        migrations.RemoveField(
            model_name='rentalusage',
            name='end_odometer',
        ),
        migrations.RemoveField(
            model_name='rentalusage',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='rentalusage',
            name='extra_hours',
        ),
        migrations.RemoveField(
            model_name='rentalusage',
            name='extra_km',
        ),
        migrations.RemoveField(
            model_name='rentalusage',
            name='extra_km_charges',
        ),
        migrations.RemoveField(
            model_name='rentalusage',
            name='start_odometer',
        ),
        migrations.RemoveField(
            model_name='rentalusage',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='deposit_paid_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded'), ('No Remaining to Refund', 'No Remaining to Refund')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='deposit_refunded_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded'), ('No Remaining to Refund', 'No Remaining to Refund')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='limits_refunded_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded'), ('No Remaining to Refund', 'No Remaining to Refund')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='remaining_paid_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded'), ('No Remaining to Refund', 'No Remaining to Refund')], default='Pending', max_length=30),
        ),
    ]
